DROP TABLE VLOGGER;

CREATE TABLE VLOGGER(
    vLoggerID NUMBER(2,0) NOT NULL,
    forename      VARCHAR2(20) NOT NULL,
    surname        VARCHAR2(20) NOT NULL,
    username        VARCHAR2(6) NOT NULL,
    expertise  VARCHAR2(15) NOT NULL);

ALTER TABLE VLOGGER
ADD CONSTRAINT VLOGGER_pk 
 PRIMARY KEY (VLOGGERID);
 
DROP TABLE VIDEO;

CREATE TABLE VIDEO(
    videoID number(1,0) NOT NULL,
    vLoggerID NUMBER(2,0) NOT NULL,
    videoName      VARCHAR2(30) NOT NULL,
    duration        NUMBER(3,0) NOT NULL,
    dateCreated DATE NOT NULL,
    content  VARCHAR2(40) NOT NULL,
    rating NUMBER (1,0) NOT NULL);

ALTER TABLE VIDEO
ADD CONSTRAINT VIDEO_pk 
 PRIMARY KEY (VIDEOID);
 
 ALTER TABLE VIDEO
 ADD CONSTRAINT video_fk
 FOREIGN KEY(vLoggerID) REFERENCES VLOGGER(vLOGGERID);
 
 ALTER TABLE VIDEO
 ADD CONSTRAINT VIDEO_ran
 CHECK ( rating between 1 and 5)
 
 
